### ISSUE TITLE
wio-event stops receiving events after some time (needs reconnect?)

### ISSUE THREAD

**Issue by mhama** [WarriorRocker/node-red-contrib-wio-seeed#1]
Thanks for the great nodes!
I'm running node-RED on my local Windows 8.1 pc.
I have a Wio Node that connects to a button module and a vibrator motor module. (just for a test)

After deployment, both the button (via wio-event) and the vibrator module (via wio-pwm) responds correctly. But several minutes later, the button stops responding, but the vibrator module still works like it should.

I used the Wio Link app to confirm that the button is alive, by GET request of the current pressed state.
So the Wio Node and the network and node-RED is working correctly, but the wio-event node is not responding.

Maybe the pc gone to sleep mode and got the websocket disconnected. It would be better to reconnect the websocket to work for longer period of time.

**Comment by WarriorRocker** [comment]
Issues with sleep and network connection drop-out should now be fixed in addition to another issue where on a redeploy of the wio-event node a duplicate connection could be made. The node now closes the connection properly and will attempt reconnection automatically every 1000ms. If there is interest in adding more control options let me know otherwise this fix should cover most use cases.

Also thanks for the detailed info as I had noticed a similar issue but had not been able to track it down at the time. Let me know if this gives you any other issue.

**Comment by mhama** [comment]
Thank you @WarriorRocker !
After update, the wio-event connection survived after wio-node reset and also node-red network disconnection. GJ!
