### ISSUE TITLE
duty parameter of PWM node is better to be handled as float.

### ISSUE THREAD

**Issue by mhama** [WarriorRocker/node-red-contrib-wio-seeed#2]
Hi,
I wanted to do accurate control of PWM (actually I want to control a (non-grove) servo) via wio-pwm. But the current implementation seems to be that it takes duty parameter as integer, rather than float, and the control of the servo angle becomes a bit rough.
https://github.com/WarriorRocker/node-red-contrib-wio-seeed/blob/master/wio-pwm/wio-pwm.js#L11
So I hope that the duty parameter will be handled as float.

Also I think that the parameters of wio-pwm will be better to be documented in "info" page. As I actually look into the source code to find that the value of the msg.payload will be set to "Auto-" values.

**Comment by WarriorRocker** [comment]
Good find, changed the parseInt to parseFloat for the duty values in accordance with the API docs. I don't have a Wio on-hand with a compatible PWM module but the API requests look valid, let me know if it gives you any issues.

I definitely want to update the docs, out of curiosity what are your opinions of the mode settings? Some Node-RED nodes prefer to use additional properties in the msg object however I went with a simpler approach utilizing just the payload values in an effort to make these nodes more drag and drop. Although I would be interested in solutions that can accommodate both paradigms since currently this package targets mostly the non-developer.

**Comment by mhama** [comment]
Please take below as a grain of salt, because I'm just a newbie about node-RED and I didn't even see many tutrials yet.

At first grance, I didn't correctly understand "Auto". I guessed that the node will automatically set some "good" values but I couldn't correctly guess the behavior.

Like some core nodes like switch node ,the node may use this field UI. The default is msg.payload and the user can use other values. I think this is neat, and easy to understand that the the node gets values from variables at first grance.
![image](https://cloud.githubusercontent.com/assets/618417/16106363/bff3a328-33ce-11e6-9773-9b52b406fc9c.png)

Also If you can use this UI that users can select from values and variables, it can be a bit simpler.
![image](https://cloud.githubusercontent.com/assets/618417/16106672/5d494cf2-33d1-11e6-8009-be177240e614.png)  (photoshopped image)

So I prefer like this:
- "Mode" Drop Down Menu
  - [Set Duty]
    - Duty
      - Variable/Constant Field UI (default: msg.payload or msg.duty)
  - [Set Duty And Frequency]
    - Duty
      - Variable/Constant Field UI (default: msg.duty)
    - Frequency
      - Variable/Constant Field UI (default: msg.freq)

Other option may be:
No drop down menus.
The node get duty value from msg.duty.
The node get frequency value from msg.freq if it is set.
The node use "Duty" mode if freq is not set. "Duty and Freq" mode if duty and freq is set.

I currently prefer former idea, as I can understand the node in a glance, and can experiment without writing javascript code, and easy to change from a constant value to a variable.

Whether msg.duty or msg.payload is better, is not that I can say now. Because I need to see info to confirm the variable name anyway.
